apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  selector:
    matchLabels:
      app: weather-app
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: vkv0220/flask:2.0
        ports:
        - containerPort: 8080
        env:
        - name: API_KEY
          value: {{ .Values.api_key }}
        - name: NAME
          value: {{ .Values.city_name }}      
